#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

WAYPOINTS_CONFIG="${REPO_ROOT}/ros2/src/drone_bringup/config/minjerk_waypoints.yaml"
OUTPUT_DIR="${REPO_ROOT}/flight_logs/of_compare"
RUN_ID=""
LOG_LEVEL="info"
EXTRA_LAUNCH_ARGS=()

usage() {
  cat <<'EOF'
Usage:
  scripts/run_minjerk_of_compare.sh [options] [-- launch_arg:=value ...]

Launch the minimum-jerk waypoint mission and mocap-vs-optical-flow logger.

Options:
  --waypoints-config PATH   Editable waypoint YAML.
  --output-dir PATH         Directory for per-run CSV/log artifacts.
  --run-id ID               Run ID. Default: generated by logger.
  --log-level LEVEL         ROS log level. Default: info
  -h, --help                Show this help.

Anything after "--" is passed directly to ros2 launch.
EOF
}

fail() {
  printf '[run_minjerk_of_compare] ERROR: %s\n' "$*" >&2
  exit 1
}

warn() {
  printf '[run_minjerk_of_compare] WARN: %s\n' "$*" >&2
}

source_ros_env() {
  local restore_nounset=0
  if [[ "$-" == *u* ]]; then
    restore_nounset=1
    set +u
  fi

  if [[ -f /opt/ros/humble/setup.bash ]]; then
    # shellcheck source=/dev/null
    source /opt/ros/humble/setup.bash
  fi
  if [[ -f "${REPO_ROOT}/ros2/install/setup.bash" ]]; then
    # shellcheck source=/dev/null
    source "${REPO_ROOT}/ros2/install/setup.bash"
  fi

  if [[ "${restore_nounset}" -eq 1 ]]; then
    set -u
  fi

  command -v ros2 >/dev/null 2>&1 || fail "ros2 is not available."
}

ensure_ros_log_dir() {
  if [[ -n "${ROS_LOG_DIR:-}" ]]; then
    mkdir -p "${ROS_LOG_DIR}" 2>/dev/null || true
    return
  fi

  local default_log_dir="${HOME:-}/.ros/log"
  if [[ -n "${HOME:-}" ]]; then
    mkdir -p "${default_log_dir}" 2>/dev/null || true
    if [[ -w "${default_log_dir}" ]]; then
      return
    fi
  fi

  export ROS_LOG_DIR="${REPO_ROOT}/log/ros_launch"
  mkdir -p "${ROS_LOG_DIR}" 2>/dev/null || true
  warn "~/.ros/log is not writable; using ROS_LOG_DIR=${ROS_LOG_DIR}"
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --waypoints-config)
      [[ $# -ge 2 ]] || fail "--waypoints-config requires a value."
      WAYPOINTS_CONFIG="$2"
      shift 2
      ;;
    --output-dir)
      [[ $# -ge 2 ]] || fail "--output-dir requires a value."
      OUTPUT_DIR="$2"
      shift 2
      ;;
    --run-id)
      [[ $# -ge 2 ]] || fail "--run-id requires a value."
      RUN_ID="$2"
      shift 2
      ;;
    --log-level)
      [[ $# -ge 2 ]] || fail "--log-level requires a value."
      LOG_LEVEL="$2"
      shift 2
      ;;
    --)
      shift
      EXTRA_LAUNCH_ARGS+=("$@")
      break
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      fail "Unknown argument: $1"
      ;;
  esac
done

[[ -f "${WAYPOINTS_CONFIG}" ]] || fail "waypoints config not found: ${WAYPOINTS_CONFIG}"
mkdir -p "${OUTPUT_DIR}"
source_ros_env
ensure_ros_log_dir

printf '[run_minjerk_of_compare] waypoints_config=%s\n' "${WAYPOINTS_CONFIG}"
printf '[run_minjerk_of_compare] output_dir=%s\n' "${OUTPUT_DIR}"
if [[ -n "${RUN_ID}" ]]; then
  printf '[run_minjerk_of_compare] run_id=%s\n' "${RUN_ID}"
fi

ros2 launch drone_bringup minjerk_of_compare.launch.py \
  log_level:="${LOG_LEVEL}" \
  waypoints_config:="${WAYPOINTS_CONFIG}" \
  output_dir:="${OUTPUT_DIR}" \
  run_id:="${RUN_ID}" \
  "${EXTRA_LAUNCH_ARGS[@]}"
